name: youtube-pull-request

on:
  pull_request:
    paths:
      - "youtube/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1
        with:
          input: "youtube"
          version: "1.11.0"
      - uses: bufbuild/buf-lint-action@v1
      # - uses: bufbuild/buf-breaking-action@v1
      #   with:
      #     input: "youtube"
      #     against: "https://github.com/${GITHUB_REPOSITORY}.git#branch=main"
