name: CI (Youtube)

on:
  pull_request:
    paths:
      - "youtube/**"

jobs:
  build:
    name:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Buf setup
        uses: bufbuild/buf-setup-action@v1

      - name: Buf lint
        uses: bufbuild/buf-lint-action@v1
        with:
          input: "youtube"

      #- name: Buf breaking
      #  uses: bufbuild/buf-breaking-action@v1
      #  with:
      #    input: "youtube"
      #    against: "https://github.com/${GITHUB_REPOSITORY}.git#branch=main,ref=HEAD~1,subdir=youtube"
