image:
  name: bufbuild/buf:1.10.0
  entrypoint: [ "" ]

stages:
  - lint
  - test
  - push

lint:
  stage: lint
  script:
    - buf lint $SUB_DIR
  allow_failure: false
  rules:
    - when: always

test:
  stage: test
  script:
    - buf build $SUB_DIR
    # - cd $SUB_DIR
    # - buf breaking --against "$CI_REPOSITORY_URL#branch=$BREAKING_BRANCH,subdir=$SUB_DIR"
  variables:
    BREAKING_BRANCH: $CI_COMMIT_BRANCH
  rules:
    - if: $TRIGGER_SOURCE == "merge"
      variables:
        BREAKING_BRANCH: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
      when: always
    - when: always
  allow_failure: false
  needs:
    - lint

push:
  stage: push
  before_script:
    - cd $SUB_DIR
    - echo $BUF_TOKEN | buf registry login --username $BUF_USER --token-stdin
  script:
    - buf push
  after_script:
    - buf registry logout
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $TRIGGER_SOURCE == "push"
      when: always
    - when: never
  needs:
    - test
